# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Page"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:



# This component is to be used on pages where an array structure
# is used to build the page on CloudCannon, and you want to enable
# live previewing. This component expects a property "content_blocks"
# to be passed that is an array of bookshop array structures.
# This component also sets a theme if provided.
