baseURL: 'http://example.org/'
languageCode: en-us
title: Urban
theme_name: ''
theme_data: ''
summaryLength: 40
module:
  replacements: components.local -> ../component-library
  imports:
    - path: components.local
    - path: github.com/cloudcannon/bookshop/hugo/v3

permalinks:
  blog: :section/:title/
