# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Gallery"
  description: "An image/link gallery"
  icon: "wysiwyg"
  tags: ["Gallery"]

# Defines the structure of this component, as well as the default values
blueprint:
  details:
    show_details: true
    heading: ""
    subheading: ""
    text_color: "#ffffff"
    button: bookshop:generic/button
  content_arrangement: "Left"
  image_borders: true
  component_theme: "Dark"
  gallery_items:
    - image: ""
      image_title: ""
      image_caption: ""
      link_url: ""


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  details:
    show_details: true
    heading: "Some of our work"
    subheading: "We take pride in our previous work and our happy customers. We cater to any sector to boost business and increase exposure."
    text_color: "#ffffff"
    button:
      label: "View Full Portfolio →"
      link_url: "/portfolio/"
      variant: "plain-text"
      submit: false
  content_arrangement: "Left" 
  image_borders: true
  component_theme: "Dark"
  gallery_items:
    - image: "//placekitten.com/400/440?a=.png"
      image_title: "Item One"
      image_caption: "Caption Text"
      link_url: "//placekitten.com/400/440?a=.png"
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_arrangement:
    type: select
    options:
      values:
        - "Left"
        - "Right"
  component_theme:
    type: select
    options:
      values:
        - "Light"
        - "Dark"
        - "Branded"
