# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Button"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: "Get Started Free"
  link_url: "/sign-up/"
  variant: "filled"
  open_in_new_tab: false
  submit: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "Get Started Free"
  link_url: "/sign-up/"
  variant: "filled"
  open_in_new_tab: false
  submit: true

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  variant:
    type: select
    options:
      values:
        - "transparent"
        - "filled"
        - "plain-text"

