# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Header With Image"
  description: "Page header with headings, a button and an image"
  icon: "wysiwyg"
  tags: ["Headers"]

# Defines the structure of this component, as well as the default values
blueprint:
  heading_html: ""
  subheading_html: ""
  text_color: "#ffffff"
  content_alignment: "Center"
  button_label: ""
  button_link_url: "/sign-up/"
  button_variant:
    select:
      - "Transparent"
      - "Filled"
  image: ""
  component_theme: "Light"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading_html: "<h1>The last sales CRM <strong>you'll ever need</strong></h1>"
  subheading_html: "<p>Track and optimize your sales team in real time.</p>"
  text_color: "#ffffff"
  content_alignment: "Center"
  button_label: "Get Started Free"
  button_link_url: "/sign-up/"
  button_variant:
    select:
      - "Transparent"
      - "Filled"
  image: "/images/dashboard.png"
  component_theme: "Light"
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
